name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Instalação de dependencias
        run: npm install
        working-directory: ./src

      - name: Execução de Teste Unitário
        run: npm test
        working-directory: ./src
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Docker build 
        uses: docker/build-push-action@v5.3.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v4.1.2
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Deploy das aplicações
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
